# A list of devices you want to take the screenshots from
devices([
  "iPhone 17 Pro Max",
  "iPhone 17 Pro",
  "iPhone 17",
  "iPhone Air",
  "iPad Pro 11-inch (M5)",
  "iPad Pro 13-inch (M5)"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("KeyokuSnapshotTests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Use Xcode's project-specific derived data to reuse cached SPM builds
# (SwiftfulGamification has a Swift 6.1 compiler bug that only fails on clean builds)
derived_data_path("#{Dir.home}/Library/Developer/Xcode/DerivedData/Keyoku-evphpcfbbjlcoheapoejwegyetpp")

# For more information about all available options run
# fastlane action snapshot
